version: '2'
services:
  zookeeper:
    container_name: kinaction-zookeeper
    image: confluentinc/cp-zookeeper:latest-ubi8.amd64
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper-data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
  broker:
    container_name: kinaction-kafka
    image: confluentinc/cp-kafka:latest-ubi8.amd64
    ports:
      - "9092:9092"
      - "9101:9101"
    restart: always
    volumes:
      - "kafka-data:/var/lib/kafka/data"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS:PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_JMX_PORT=9101
      - KAFKA_JMX_HOSTNAME=localhost
      - CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS:broker:29092
      - CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS=1
      - CONFLUENT_METRICS_ENABLE='true'
      - CONFLUENT_SUPPORT_CUSTOMER_ID='anonymous'
    depends_on:
      - zookeeper

volumes:
  kafka-data:
    driver: local
  zookeeper-data:
    driver: local